n=input("digite algo:")
print("O tipo primitivo desse valor é", type(n))
print(bool(n.isalnum))
print(bool(n.isalpha))
print(bool(n.isspace))
print(bool(n.isdigit))
print(n.istitle())
print(n.lstrip())
print(n.islower())